### ISSUE TITLE
New File types

### ISSUE THREAD

**Issue by yurividal** [jniggemann/filebrowser-css#2]
Hi.
Any chance you can add branding for the following file types?
.sh
.py
.conf
.yaml

This is most of thr files i have in my filebrowser instance and none of these re colored. =)

**Comment by jniggemann** [comment]
> Any chance you can add branding for the following file types?

Which icon and color do you propose?
Those 4 are text files, but they are not the same "category" of files. While .sh and .py are scripts / programs, .conf and .yaml are something else...

**Comment by yurividal** [comment]
To be honest, i didnt really think (or care) what colors get used. Just
wanted them to be different, since thats most of what i have in my
filebrowser and it currently looks all white.

**Comment by jniggemann** [comment]
OK, so if I understand correctly, you don't care about colors, only about the icons.
Which icon do you propose using for these extensions?

**Comment by yurividal** [comment]
Yeah, i dont mind what colors they get, and I think their current icons are
also fine. Up to you.
As long as the colors are different it makes it easier to identify!

Thank you!

**Comment by jniggemann** [comment]
OK, so it's the other way round: You don't care about the icon, only about the color?
Thinking about this, I guess it's better to not implement this: The CSS file is meant for a broad audience, and your usecase looks like an edge case to me.

But you can do this yourself, just add the below code and substitute yaml for the desired file extensions.

```
#listing .item[aria-label$=".yaml"] div i {
    color: #a268a1;
}
```

**Comment by jniggemann** [comment]
Oh, sry, wrong state.
