### ISSUE TITLE
Cant make it work in Lan and Web in Unraid

### ISSUE THREAD

**Issue by masterwishx** [jniggemann/filebrowser-css#3]
Founded in https://forums.unraid.net/topic/78481-support-knex666-filebrowser/page/7/

Using Unraid Docker + nginx + cloudflare
Strange but cant make custom.css to work ,not in local 192...199 not in web 
copyed to filebrowser/style , tryed  /srv/style , also made path in container:

![image png 75a31cdd7139520fc63dcc11cd6d96f3](https://github.com/jniggemann/filebrowser-css/assets/28630321/5ea800fa-1162-477e-9f31-98c6f5a00b9d)
![image png fc4c146f14f568c325ca2e31f5c005fe](https://github.com/jniggemann/filebrowser-css/assets/28630321/f7fa8bad-2127-4f64-93c7-6612b043ce04)
![image png 6e2f58fe1e16e71833af199aff198b5e](https://github.com/jniggemann/filebrowser-css/assets/28630321/d1dd29fd-175a-4c87-a8e0-d70ad093ff17)

**Comment by jniggemann** [comment]
Sorry, no idea about unraid and how it handles docker containers. Your best bet is to hope someone in the linked thread can answer this.

**Comment by masterwishx** [comment]
i saw in thread there is no problems , Unraid use regular Docker Containers , also installed on Oracle cloud without problems but used s6 Filebrowser image ...

**Comment by masterwishx** [comment]
Problem Solved , file was not in raw format ! :(
